// flow-typed signature: 7d45d86f25741c2b62b2dc71ec7b2514
// flow-typed version: <<STUB>>/serve-favicon_v^2.3.2/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serve-favicon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'serve-favicon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'serve-favicon/index' {
  declare module.exports: $Exports<'serve-favicon'>;
}
declare module 'serve-favicon/index.js' {
  declare module.exports: $Exports<'serve-favicon'>;
}
