// flow-typed signature: 8c6dd2258b2d1ac45ddb9d70b61516b0
// flow-typed version: <<STUB>>/sinon_v^2.0.0-pre.5/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sinon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sinon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sinon/lib/sinon' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/assert' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/behavior' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/call' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/collection' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/extend' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/match' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/mock-expectation' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/mock' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/sandbox' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/spy' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/stub' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/typeOf' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util-ie/timers' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util-ie/xdr' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util-ie/xhr' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/core/called-in-order' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/core/create' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/core/deep-equal' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/core/default-config' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/core/deprecated' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/core/format' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/core/function-name' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/core/function-to-string' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/core/get-config' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/core/get-property-descriptor' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/core/index' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/core/log_error' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/core/object-keys' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/core/order-by-first-call' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/core/restore' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/core/times-in-words' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/core/value-to-string' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/core/walk' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/core/wrap-method' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/event' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/fake_server_with_clock' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/fake_server' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/fake_timers' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/fake_xdomain_request' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/fake_xml_http_request' {
  declare module.exports: any;
}

declare module 'sinon/pkg/sinon-2.0.0-pre.5' {
  declare module.exports: any;
}

declare module 'sinon/pkg/sinon-ie-2.0.0-pre.5' {
  declare module.exports: any;
}

declare module 'sinon/pkg/sinon-ie' {
  declare module.exports: any;
}

declare module 'sinon/pkg/sinon-server-2.0.0-pre.5' {
  declare module.exports: any;
}

declare module 'sinon/pkg/sinon-server' {
  declare module.exports: any;
}

declare module 'sinon/pkg/sinon' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sinon/lib/sinon.js' {
  declare module.exports: $Exports<'sinon/lib/sinon'>;
}
declare module 'sinon/lib/sinon/assert.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/assert'>;
}
declare module 'sinon/lib/sinon/behavior.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/behavior'>;
}
declare module 'sinon/lib/sinon/call.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/call'>;
}
declare module 'sinon/lib/sinon/collection.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/collection'>;
}
declare module 'sinon/lib/sinon/extend.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/extend'>;
}
declare module 'sinon/lib/sinon/match.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/match'>;
}
declare module 'sinon/lib/sinon/mock-expectation.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/mock-expectation'>;
}
declare module 'sinon/lib/sinon/mock.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/mock'>;
}
declare module 'sinon/lib/sinon/sandbox.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/sandbox'>;
}
declare module 'sinon/lib/sinon/spy.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/spy'>;
}
declare module 'sinon/lib/sinon/stub.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/stub'>;
}
declare module 'sinon/lib/sinon/typeOf.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/typeOf'>;
}
declare module 'sinon/lib/sinon/util-ie/timers.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util-ie/timers'>;
}
declare module 'sinon/lib/sinon/util-ie/xdr.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util-ie/xdr'>;
}
declare module 'sinon/lib/sinon/util-ie/xhr.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util-ie/xhr'>;
}
declare module 'sinon/lib/sinon/util/core/called-in-order.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/core/called-in-order'>;
}
declare module 'sinon/lib/sinon/util/core/create.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/core/create'>;
}
declare module 'sinon/lib/sinon/util/core/deep-equal.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/core/deep-equal'>;
}
declare module 'sinon/lib/sinon/util/core/default-config.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/core/default-config'>;
}
declare module 'sinon/lib/sinon/util/core/deprecated.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/core/deprecated'>;
}
declare module 'sinon/lib/sinon/util/core/format.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/core/format'>;
}
declare module 'sinon/lib/sinon/util/core/function-name.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/core/function-name'>;
}
declare module 'sinon/lib/sinon/util/core/function-to-string.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/core/function-to-string'>;
}
declare module 'sinon/lib/sinon/util/core/get-config.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/core/get-config'>;
}
declare module 'sinon/lib/sinon/util/core/get-property-descriptor.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/core/get-property-descriptor'>;
}
declare module 'sinon/lib/sinon/util/core/index.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/core/index'>;
}
declare module 'sinon/lib/sinon/util/core/log_error.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/core/log_error'>;
}
declare module 'sinon/lib/sinon/util/core/object-keys.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/core/object-keys'>;
}
declare module 'sinon/lib/sinon/util/core/order-by-first-call.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/core/order-by-first-call'>;
}
declare module 'sinon/lib/sinon/util/core/restore.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/core/restore'>;
}
declare module 'sinon/lib/sinon/util/core/times-in-words.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/core/times-in-words'>;
}
declare module 'sinon/lib/sinon/util/core/value-to-string.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/core/value-to-string'>;
}
declare module 'sinon/lib/sinon/util/core/walk.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/core/walk'>;
}
declare module 'sinon/lib/sinon/util/core/wrap-method.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/core/wrap-method'>;
}
declare module 'sinon/lib/sinon/util/event.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/event'>;
}
declare module 'sinon/lib/sinon/util/fake_server_with_clock.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/fake_server_with_clock'>;
}
declare module 'sinon/lib/sinon/util/fake_server.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/fake_server'>;
}
declare module 'sinon/lib/sinon/util/fake_timers.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/fake_timers'>;
}
declare module 'sinon/lib/sinon/util/fake_xdomain_request.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/fake_xdomain_request'>;
}
declare module 'sinon/lib/sinon/util/fake_xml_http_request.js' {
  declare module.exports: $Exports<'sinon/lib/sinon/util/fake_xml_http_request'>;
}
declare module 'sinon/pkg/sinon-2.0.0-pre.5.js' {
  declare module.exports: $Exports<'sinon/pkg/sinon-2.0.0-pre.5'>;
}
declare module 'sinon/pkg/sinon-ie-2.0.0-pre.5.js' {
  declare module.exports: $Exports<'sinon/pkg/sinon-ie-2.0.0-pre.5'>;
}
declare module 'sinon/pkg/sinon-ie.js' {
  declare module.exports: $Exports<'sinon/pkg/sinon-ie'>;
}
declare module 'sinon/pkg/sinon-server-2.0.0-pre.5.js' {
  declare module.exports: $Exports<'sinon/pkg/sinon-server-2.0.0-pre.5'>;
}
declare module 'sinon/pkg/sinon-server.js' {
  declare module.exports: $Exports<'sinon/pkg/sinon-server'>;
}
declare module 'sinon/pkg/sinon.js' {
  declare module.exports: $Exports<'sinon/pkg/sinon'>;
}
