// flow-typed signature: 42bd0527d8d726f7ad1514212813f3f4
// flow-typed version: <<STUB>>/stylelint-webpack-plugin_v^0.6.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-webpack-plugin/lib/constants' {
  declare module.exports: any;
}

declare module 'stylelint-webpack-plugin/lib/lint-dirty-modules-plugin' {
  declare module.exports: any;
}

declare module 'stylelint-webpack-plugin/lib/linter' {
  declare module.exports: any;
}

declare module 'stylelint-webpack-plugin/lib/run-compilation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-webpack-plugin/index' {
  declare module.exports: $Exports<'stylelint-webpack-plugin'>;
}
declare module 'stylelint-webpack-plugin/index.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin'>;
}
declare module 'stylelint-webpack-plugin/lib/constants.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/lib/constants'>;
}
declare module 'stylelint-webpack-plugin/lib/lint-dirty-modules-plugin.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/lib/lint-dirty-modules-plugin'>;
}
declare module 'stylelint-webpack-plugin/lib/linter.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/lib/linter'>;
}
declare module 'stylelint-webpack-plugin/lib/run-compilation.js' {
  declare module.exports: $Exports<'stylelint-webpack-plugin/lib/run-compilation'>;
}
